version: '3.4'

services:
  db:
    image: library/mysql:5.7
    container_name: dotplay-mysql
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
  # dotplayapi:
  #   image: dotplayapi

  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #     MYSQL_HOST: localhost
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_DB: mysql
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   command:
  #     - bash
  #     - -c
  #     - |
  #       /app/wait-for-it.sh db:3306 -t 10
  #       npm run start:dev
  #   volumes:
  #     - .:/dotplay-api/src/app
  #     - /dotplay-api/src/app/node_modules
