version: '3.4'

services:
  dotplayapi:
    image: dotplayapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3500:3500
